### ISSUE TITLE
Unlicensed

### ISSUE THREAD

**Issue by AlexanderKyron** [DataDink/WindowScrape#6]
Hi! I would love to use this library in my WinTile Windows Shell replacement/augmentation, but there is no license attached to the repository so I just want to ensure I am following your intentions for how your code is used and redistributed.

Could you please determine an appropriate license and add it or at least explicitly name it here? 

For my purposes compatibility with the GPL is ideal but of course it's your project :)

**Comment by DataDink** [comment]
Added public domain / unlicense
